import { COLORS } from "../constants/theme";

export const stylesheet = {
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "left",
    backgroundColor: COLORS.white,
  },
  title: {
    fontWeight: "600",
    fontSize: 25,
    textAlign: "left",
    color: COLORS.grey,
  },
  text: {
    fontSize: 15,
    marginVertical: 3,
    color: COLORS.grey,
  },
  textWhite: {
    fontSize: 15,
    marginVertical: 2,
    color: "white",
  },
  button: {
    backgroundColor: "#EE574E",
    width: "100%",
    height: 45,
    justifyContent: "center",
    padding: 10,
    paddingHorizontal: 30,
    borderRadius: 5,
    alignItems: "center",
    marginTop: 20,
  },
  buttonText: {
    color: "white",
    fontWeight: "500",
    fontSize: 16,
  },
  outlineButton: {
    backgroundColor: "none",
    borderWidth: 2,
    height: 45,
    justifyContent: "center",
    borderColor: COLORS.lightbeige,
    width: "100%",
    padding: 8,
    paddingHorizontal: 30,
    borderRadius: 5,
    alignItems: "center",
    marginTop: 20,
  },
  outlineButtonText: {
    color: COLORS.lightbeige,
    fontWeight: "500",
    fontSize: 16,
  },
  colorOutlineButton: {
    backgroundColor: "none",
    borderWidth: 2,
    borderColor: COLORS.red,
    width: "100%",
    height: 45,
    justifyContent: "center",
    padding: 8,
    paddingHorizontal: 30,
    borderRadius: 5,
    alignItems: "center",
    marginTop: 10,
  },
  colorOutlineButtonText: {
    color: COLORS.red,
    fontWeight: "500",
    fontSize: 16,
  },
  input: {
    fontSize: 16,
    backgroundColor: "white",
    borderColor: COLORS.lightgrey,
    borderWidth: 1,
    borderRadius: 8,
    marginBottom: 0,
    height: 40,
    paddingLeft: 10,
    color: COLORS.grey,
  },
  label: {
    fontSize: 16,
    marginBottom: 0,
    marginTop: 0,
    fontWeight: "bold",
    color: COLORS.grey,
  },
  smallLabel: {
    fontSize: 15,
    fontWeight: "500",
    color: COLORS.grey,
  },
  itemLabel: {
    fontWeight: "bold",
    textTransform: "uppercase",
    marginVertical: 5,
    marginRight: 0,
    color: COLORS.grey,
  },
  whiteItemLabel: {
    fontWeight: "bold",
    textTransform: "uppercase",
    marginVertical: 5,
    marginRight: 0,
    color: "white",
  },
  roundButton: {
    backgroundColor: COLORS.red,
    alignItems: "center",
    justifyContent: "center",
    width: 210,
    position: "absolute",
    bottom: 10,
    right: 40,
    height: 50,
    borderRadius: 100,
  },
  dropdown1BtnStyle: {
      width: '100%',
      height: 40,
      backgroundColor: '#FFF',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: COLORS.lightgrey,
      color: COLORS.grey,
  },
  dropdown1BtnTxtStyle: {
    color: COLORS.grey,
    textAlign: "left",
  },
  myCard: {
    backgroundColor: 'white',
    borderRadius: 8,
    margin: 20,
    padding: 30,
  },
  shadowProp: {
    shadowColor: 'grey',
    shadowOffset: {width: -1, height: 4},
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  shareButton: {
    position: "absolute",
    right: 5,
    bottom: 20,
  },
  catIcon: {
    width: 80,
    height: 80,
    borderRadius: 100,
  }
};