import { COLORS } from "../constants/theme";

export const stylesheet = {
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "left",
    backgroundColor: COLORS.lightbeige,
  },
  title: {
    fontWeight: "bold",
    fontSize: 25,
    textAlign: "left",
  },
  text: {
    fontWeight: "bold",
    fontSize: 15,
    marginVertical: 5,
  },
  button: {
    backgroundColor: "#EE574E",
    width: "100%",
    padding: 10,
    paddingHorizontal: 30,
    borderRadius: 5,
    alignItems: "center",
    marginTop: 20,
  },
  buttonText: {
    color: "white",
    fontWeight: "500",
    fontSize: 16,
  },
  outlineButton: {
    backgroundColor: "none",
    borderWidth: 2,
    borderColor: "#EE574E",
    width: "100%",
    padding: 8,
    paddingHorizontal: 30,
    borderRadius: 5,
    alignItems: "center",
    marginTop: 20,
  },
  outlineButtonText: {
    color: "#EE574E",
    fontWeight: "500",
    fontSize: 16,
  },
  input: {
    fontSize: 16,
    backgroundColor: "white",
    borderColor: COLORS.darkbeige,
    borderWidth: 1,
    borderRadius: 2,
    marginBottom: 0,
    height: 35,
    paddingLeft: 10,
    color: "#3F5362",
  },
  label: {
    fontSize: 17,
    marginBottom: 5,
    marginTop: 10,
    fontWeight: "bold",
  },
  smallLabel: {
    fontSize: 15,
    fontWeight: "bold",
  },
  itemLabel: {
    fontWeight: "bold",
    textTransform: "uppercase",
    marginVertical: 5,
    marginRight: 100,
  },
  roundButton: {
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.2)",
    alignItems: "center",
    justifyContent: "center",
    width: 70,
    position: "absolute",
    bottom: 10,
    right: 10,
    height: 70,
    backgroundColor: "#fff",
    borderRadius: 100,
  },
  dropdown1BtnStyle: {
      width: '100%',
      height: 40,
      backgroundColor: '#FFF',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#444',
  },
  myCard: {
    backgroundColor: 'white',
    borderRadius: 8,
    margin: 20,
    padding: 20,
  },
  shadowProp: {
    shadowColor: 'grey',
    shadowOffset: {width: -1, height: 4},
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
};